const apps = [
  {
    id: "firefox",
    component: "Firefox",
    title: "Firefox Browser",
    icon: "./themes/Yaru/apps/firefox.svg",
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    meta: {},
  },
  {
    id: "todo-ist",
    component: "ToDoList",
    title: "Todoist",
    icon: "./themes/Yaru/apps/todoist.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "about-obj9527",
    component: "AboutObj9527",
    title: "About Obj9527",
    icon: "./themes/Yaru/system/user-home.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    meta: {},
  },
  {
    id: "blog",
    component: "Blog",
    title: "My Blog",
    icon: "./themes/Yaru/apps/blog.svg",
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    meta: {},
  },
  {
    id: "vscode",
    component: "VSCode",
    title: "Visual Studio Code",
    icon: "./themes/Yaru/apps/vscode.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "terminal",
    component: "Terminal",
    title: "Terminal",
    icon: "./themes/Yaru/apps/bash.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "music",
    component: "CloudMusic",
    title: "Music",
    icon: "./themes/Yaru/apps/vue-aplayer-round.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "settings",
    component: "Settings",
    title: "Settings",
    icon: "./themes/Yaru/apps/gnome-control-center.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "trash",
    component: "Trash",
    title: "Trash",
    icon: "./themes/Yaru/system/user-trash-full.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: false,
    meta: {},
  },
  {
    id: "gedit",
    component: "Gedit",
    title: "Send a Message",
    icon: "./themes/Yaru/apps/gedit.png",
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    meta: {},
  },
];
export default apps;
